version: '2.1'

services:
  nginx:
    container_name: ${SYLIUS_NAME}-nginx
    image: nginx:1.13
    ports:
      - ${SYLIUS_PORT}:80
    volumes:
      - ./nginx/sylius.conf:/etc/nginx/nginx.conf
      - ./sylius:/var/www/html
    networks:
      - sylius-network

  phpfpm:
    container_name: ${SYLIUS_NAME}-phpfpm
    build:
      context: ./phpfpm
    environment:
      - SYLIUS_DATABASE_HOST=mysql
      - SYLIUS_DATABASE_USER=sylius
      - SYLIUS_DATABASE_PASSWORD=sylius
      - SYLIUS_MAILER_HOST=mailhog:1025
      - SYLIUS_APP_DEV_PERMITTED=1
    command: php-fpm -F --allow-to-run-as-root
    volumes:
      - ./sylius:/var/www/html
    networks:
      - sylius-network

  mysql:
    container_name: ${SYLIUS_NAME}-mysql
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    ports:
      - 127.0.0.1:${DB_PORT}:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - sylius-network

  mailhog:
    container_name: ${SYLIUS_NAME}-mailhog
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
    networks:
      - sylius-network

  nodejs:
    container_name: ${SYLIUS_NAME}-nodejs
    image: node:latest
    volumes:
      - ./sylius:/var/www/html

networks:
  sylius-network:
    driver: "bridge"

